---
   - name: Add elasticsearch repo key
     apt_key: id=D88E42B4 url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

   - name: Add repo to apt list
     apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.4/debian stable main' state=present

   - name: Install logstash
     apt: pkg=logstash={{ logstash_version }} update_cache=yes cache_valid_time=3600

   - name: Install logstash-contrib
     apt: pkg=logstash-contrib={{ logstash_contrib_version }} update_cache=yes cache_valid_time=3600

   - name: Enable logstash
     service: name=logstash enabled=yes state=started
