---
- hosts: sensu-server
  sudo: yes
  gather_facts: yes
  
  vars:
    instance_roles: 
        - base
  roles:
    - common
    - install-sensu-server
    - config-sensu-server
    - install-sensu-dashboard
    - install-sensu-client
    - config-sensu-client 
    - install-beaver
    - config-beaver
