---
   - name: Add elasticsearch repo key
     apt_key: id=D88E42B4 url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

   - name: Add repo to apt list
     apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.3/debian stable main' state=present

   - name: Install elasticsearch
     apt: pkg=elasticsearch={{ elasticsearch_version }} update_cache=yes cache_valid_time=3600

   - name: Install OpenJDK-7-jre-headless
     apt: pkg=openjdk-7-jre-headless state=latest update_cache=yes cache_valid_time=3600

   - name: Enable elasticsearch
     service: name=elasticsearch enabled=yes state=started
