---
   - name: Install Redis
     apt: pkg=redis-server={{ redis_version}} state=present update_cache=yes cache_valid_time=3600

   - name: Enable Redis
     service: name=redis-server enabled=yes state=started
